### ISSUE TITLE
Update Travis-CI configuration

### ISSUE THREAD

**Issue by cbj4074** [indiehd/velkart#43]
Each build has warning/infos:

```
Build config validation 
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing dist, using the default xenial
root: missing os, using the default linux
```

Specific values should be provided for each.

**Comment by poppabear8883** [comment]
Closing this issue in favor of Github Actions.

Discussion: https://discord.com/channels/474753427583270922/496681546682728448/920688561622237214
